name: Build and deploy Node.js app to Azure Web App - obms-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Navigate to backend directory
        run: cd backend  # Navigate to the backend directory where package.json is located

      - name: npm install, build, and test
        run: |
          cd backend  # Ensure we are still in the backend folder
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .  # Upload the whole project or the backend directory (adjust based on what you want)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'obms-backend'
          slot-name: 'Production'
          package: .  # Ensure the correct package is being deployed (adjust based on your artifact structure)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_78471D7F9D0A47F38989631FB0EBB639 }}
